spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user
          keycloak:
            provider: keycloak
            client-id: example-client
            client-secret: secret
            scope:
              - openid
              - profile
        provider:
          keycloak:
            issuer-uri: http://localhost:8888/realms/example-realm
            user-name-attribute: preferred_username